NOT_INPUT_USERNAME_OR_PASSWORD = '请输入用户名或密码'
USERNAME_OR_PASSWORD_ERROR = '用户名或密码错误'
USERNAME_ALREADY_EXIST = '用户名已存在'
LOGIN_SUCCESS = '登录成功'

FLOW_CHART_NOT_EXISTS_ERROR = '该流程不存在'
FLOW_CHART_ALREADY_EXIST_ERROR = '该流程名称已存在'

REQUEST_SUCCESS = '请求成功'

ACTION_SUCCESS = '操作成功'

WHITE_LIST = []

ENCODE_STRING = 'utf-8'
